---
title: "P8105 Homework 2"
author: "Kiran Kui"
date: "`r Sys.Date()`"
output: github_document
---

## Load Libraries 

```{r setup}

library(tidyverse)
library(readxl)
```

e want to read and clean the NYC transit dataset from the csv file. 

```{r Read/Clean Transit data, eval = FALSE}
NYC_transit <- read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names()

skimr::skim(NYC_transit)
```

Now, we want to retain the following variables:

* line
* station name
* station latitude / longitude
* routes served
* entry
* vending
* entrance type
* ADA compliance 

```{r retain variables, eval = FALSE}
select(NYC_transit, line, station_name, station_latitude, station_longitude, route1, route2, route3, route4, route5, route6, route7, route8, route9, route10, route11, entry, vending, entrance_type, ada)

NYC_transit
```


Converting the entry variable into a logical vector. 
```{r converting to logical vector, eval = FALSE}

recode(NYC_transit$entry, "YES"=TRUE,"NO"=FALSE, .default = NA)

NYC_transit
```
